### ISSUE TITLE
Error in TLSCertificate Function missing t.

### ISSUE THREAD

**Issue by YAPMKES** [salrashid123/signer#19]
https://github.com/salrashid123/signer/blame/0e96f7d4c37c54e5749d1a334d05e4eb5ffeec33/kms/kms.go#L115

Certificate: [][]byte{x509Certificate.Raw}, should probably be Certificate: [][]byte{t.x509Certificate.Raw},
probably the module global variable  "x509Certificate x509.Certificate"  on line 31 is no longer needed.

**Comment by salrashid123** [comment]
thanks, fixed it in last commit just now and bumped the references here too
  https://github.com/salrashid123/kms_golang_signer
